#!/usr/bin/env python3
"""
ICR2 Building Generator (UI + .3D writer)

Standalone Tkinter application that generates Papyrus/Icr2 .3D building objects.

Supported roof types
- flat
- parapet (inset roof cap)
- gable (simple pitched roof)
- pyramid (4-sided pitched roof)

No external libraries required.
"""

import tkinter as tk
from tkinter import ttk, filedialog, messagebox
from pathlib import Path
import configparser


INI_PATH = Path(__file__).with_suffix(".ini")


# ------------------------------------------------------------
# Geometry generation
# ------------------------------------------------------------

def generate_base(width, depth, height):
    verts = {}

    verts["a0"] = (0, depth, 0)
    verts["b0"] = (0, 0, 0)
    verts["c0"] = (width, 0, 0)
    verts["d0"] = (width, depth, 0)

    verts["a1"] = (0, depth, height)
    verts["b1"] = (0, 0, height)
    verts["c1"] = (width, 0, height)
    verts["d1"] = (width, depth, height)

    faces = [
        ("ls1", ["a1","a0","b0","b1"]),
        ("fr1", ["b1","b0","c0","c1"]),
        ("rs1", ["c1","c0","d0","d1"]),
        ("bk1", ["d1","d0","a0","a1"]),
    ]

    return verts, faces


def add_flat_roof(faces):
    faces += [
        ("topB", ["a1", "b1", "c1"]),
        ("topD", ["a1", "c1", "d1"]),
    ]


def add_parapet_roof(verts, faces, width, depth, height, inset, roof_height):

    verts["a2"] = (inset, depth-inset, height+roof_height)
    verts["b2"] = (inset, inset, height+roof_height)
    verts["c2"] = (width-inset, inset, height+roof_height)
    verts["d2"] = (width-inset, depth-inset, height+roof_height)

    faces += [
        ("ls2", ["a2","a1","b1","b2"]),
        ("fr2", ["b2","b1","c1","c2"]),
        ("rs2", ["c2","c1","d1","d2"]),
        ("bk2", ["d2","d1","a1","a2"]),
        ("roofB", ["a2", "b2", "c2"]),
        ("roofD", ["a2", "c2", "d2"]),
    ]


def add_gable_roof(verts, faces, width, depth, height, rise):

    verts["r0"] = (width//2, 0, height+rise)
    verts["r1"] = (width//2, depth, height+rise)

    faces += [
        ("roofL", ["a1","b1","r0","r1"]),
        ("roofR", ["c1","d1","r1","r0"]),
        ("gableF",["b1","c1","r0"]),
        ("gableB",["d1","a1","r1"])
    ]


def add_pyramid_roof(verts, faces, width, depth, height, rise):

    verts["p0"] = (width // 2, depth // 2, height + rise)

    faces += [
        ("pyrF", ["b1", "c1", "p0"]),
        ("pyrR", ["c1", "d1", "p0"]),
        ("pyrB", ["d1", "a1", "p0"]),
        ("pyrL", ["a1", "b1", "p0"]),
    ]


def generate_building(width, depth, height, roof_type, inset, roof_height, gable_rise, pyramid_rise):

    verts, faces = generate_base(width, depth, height)

    if roof_type == "flat":
        add_flat_roof(faces)

    elif roof_type == "parapet":
        add_parapet_roof(verts, faces, width, depth, height, inset, roof_height)

    elif roof_type == "gable":
        add_gable_roof(verts, faces, width, depth, height, gable_rise)

    elif roof_type == "pyramid":
        add_pyramid_roof(verts, faces, width, depth, height, pyramid_rise)

    return verts, faces


# ------------------------------------------------------------
# .3D writer
# ------------------------------------------------------------

def write_3d(path, verts, faces, parameters):

    roof_bright = int(parameters["roof_color_bright"])
    roof_dark = int(parameters["roof_color_dark"])
    side_bright = int(parameters["side_color_bright"])
    side_dark = int(parameters["side_color_dark"])

    def color_for_face(name):
        roof_bright_faces = {"topB", "roofB", "roofL", "gableF", "pyrF", "pyrL"}
        roof_dark_faces = {"topD", "roofD", "roofR", "gableB", "pyrR", "pyrB"}
        side_bright_faces = {"ls1", "fr1", "ls2", "fr2"}
        side_dark_faces = {"rs1", "bk1", "rs2", "bk2"}

        if name in roof_bright_faces:
            return roof_bright
        if name in roof_dark_faces:
            return roof_dark
        if name in side_bright_faces:
            return side_bright
        if name in side_dark_faces:
            return side_dark
        return side_bright

    lines = []
    lines.append("3D VERSION 3.0;")
    lines.append("% Generated by ICR2 Building Generator")
    for key, value in parameters.items():
        lines.append(f"% {key}: {value}")
    lines.append("")
    lines.append("nil: NIL;")

    for name in verts:
        x,y,z = verts[name]
        lines.append(f"{name}: [<{x}, {y}, {z}>];")

    lines.append("")

    for name,vs in faces:
        v = ", ".join(vs)
        lines.append(f"{name}: POLY <{color_for_face(name)}> {{{v}}};")

    lines.append("")

    prev = "nil"

    for i,(name,vs) in enumerate(faces):
        v1,v2,v3 = vs[:3]
        node = f"o{i}"
        lines.append(f"{node}: BSPF ({v1}, {v2}, {v3}), nil, {name}, {prev};")
        prev = node

    v1,v2,v3 = faces[-1][1][:3]
    lines.append(f"root: BSPF ({v1}, {v2}, {v3}), nil, {faces[-1][0]}, {prev};")

    with open(path,"w") as f:
        f.write("\n".join(lines))


# ------------------------------------------------------------
# UI
# ------------------------------------------------------------

def generate_clicked():

    try:

        width = int(width_var.get())
        depth = int(depth_var.get())
        height = int(height_var.get())

        inset = int(inset_var.get())
        roof_height = int(roof_height_var.get())
        gable_rise = int(gable_var.get())
        pyramid_rise = int(pyramid_var.get())

        roof = roof_var.get()

        save_settings()

        verts,faces = generate_building(
            width,
            depth,
            height,
            roof,
            inset,
            roof_height,
            gable_rise,
            pyramid_rise,
        )

        path = filedialog.asksaveasfilename(
            defaultextension=".3D",
            filetypes=[("3D files","*.3D")]
        )

        if not path:
            return

        params = {
            "width": width,
            "depth": depth,
            "height": height,
            "roof_type": roof,
            "parapet_inset": inset,
            "parapet_height": roof_height,
            "gable_rise": gable_rise,
            "pyramid_rise": pyramid_rise,
            "sunny_pcx": sunny_var.get(),
            "roof_color_bright": int(roof_bright_var.get()),
            "roof_color_dark": int(roof_dark_var.get()),
            "side_color_bright": int(side_bright_var.get()),
            "side_color_dark": int(side_dark_var.get()),
        }

        write_3d(path, verts, faces, params)

        messagebox.showinfo("Success","Building generated successfully.")

    except Exception as e:
        messagebox.showerror("Error",str(e))


def load_settings():
    config = configparser.ConfigParser()
    config.read(INI_PATH)
    return config


def save_settings():
    config = configparser.ConfigParser()
    config["paths"] = {"sunny_pcx": sunny_var.get()}
    with open(INI_PATH, "w", encoding="utf-8") as ini_file:
        config.write(ini_file)


def load_sunny_pcx_clicked():
    path = filedialog.askopenfilename(
        title="Select sunny.pcx",
        filetypes=[("PCX files", "*.pcx"), ("All files", "*.*")],
    )
    if not path:
        return
    sunny_var.set(path)
    save_settings()


# ------------------------------------------------------------
# Build window
# ------------------------------------------------------------

def build_window():

    global root
    global frame
    global width_var
    global depth_var
    global height_var
    global inset_var
    global roof_height_var
    global gable_var
    global pyramid_var
    global roof_var
    global sunny_var
    global roof_bright_var
    global roof_dark_var
    global side_bright_var
    global side_dark_var
    global row

    root = tk.Tk()
    root.title("ICR2 Building Generator")

    settings = load_settings()
    sunny_default = settings.get("paths", "sunny_pcx", fallback="")

    menu_bar = tk.Menu(root)
    file_menu = tk.Menu(menu_bar, tearoff=0)
    file_menu.add_command(label="Load sunny.pcx...", command=load_sunny_pcx_clicked)
    menu_bar.add_cascade(label="File", menu=file_menu)
    root.config(menu=menu_bar)

    frame = ttk.Frame(root,padding=15)
    frame.pack()

    width_var = tk.StringVar(value="320")
    depth_var = tk.StringVar(value="1042")
    height_var = tk.StringVar(value="100")

    inset_var = tk.StringVar(value="30")
    roof_height_var = tk.StringVar(value="15")

    gable_var = tk.StringVar(value="50")
    pyramid_var = tk.StringVar(value="50")

    roof_var = tk.StringVar(value="flat")
    sunny_var = tk.StringVar(value=sunny_default)
    roof_bright_var = tk.StringVar(value="200")
    roof_dark_var = tk.StringVar(value="201")
    side_bright_var = tk.StringVar(value="202")
    side_dark_var = tk.StringVar(value="203")

    row = 0

    def field(label,var):

        global row

        ttk.Label(frame,text=label).grid(row=row,column=0,sticky="w",padx=5,pady=4)
        ttk.Entry(frame,textvariable=var,width=10).grid(row=row,column=1)

        row+=1


    field("Width",width_var)
    field("Depth",depth_var)
    field("Height",height_var)

    ttk.Label(frame,text="Roof Type").grid(row=row,column=0,sticky="w",padx=5)
    ttk.OptionMenu(frame,roof_var,"flat","flat","parapet","gable","pyramid").grid(row=row,column=1)
    row+=1

    field("Parapet Inset",inset_var)
    field("Parapet Height",roof_height_var)

    field("Gable Rise",gable_var)
    field("Pyramid Rise",pyramid_var)
    field("Roof Color (Bright)", roof_bright_var)
    field("Roof Color (Dark)", roof_dark_var)
    field("Side Color (Bright)", side_bright_var)
    field("Side Color (Dark)", side_dark_var)

    ttk.Label(frame,text="sunny.pcx").grid(row=row,column=0,sticky="w",padx=5,pady=4)
    ttk.Entry(frame,textvariable=sunny_var,width=30).grid(row=row,column=1)
    row += 1

    ttk.Button(
        frame,
        text="Generate .3D",
        command=generate_clicked
    ).grid(row=row,columnspan=2,pady=15)

    root.mainloop()


if __name__ == "__main__":
    build_window()
