[metadata]
name = icr2tools
version = 0.5.0
author = SK Chow
description = A suite of modern modding utilities for IndyCar Racing II
long_description = file: README.md
long_description_content_type = text/markdown
license = MIT

[options]
packages = find_namespace:
python_requires = >=3.9
include_package_data = True

[options.package_data]
sg_viewer =
    *.ico
    *.ini
    *.json
    *.png
    help/*.html
    model/*.ini
    rendering/*.ini
track_viewer =
    *.csv
    *.ini
    help/*.html
texture_tools =
    *.ini
tso_generator =
    *.ini
    *.json
icr2timing =
    *.ini
    assets/*.ico
    assets/*.png
    ui/*.ui

[options.entry_points]
console_scripts =
    icr2-timing = icr2timing.main:main
    sg-viewer = sg_viewer.main:main
    track-viewer = track_viewer.main:main
    texture-tools = texture_tools.main:main
    trk23d = icr2_core.trk.trk23d_cli:main
