import configparser
from pathlib import Path

from tso_generator.tso_generator import (
    TEMPLATE_SECTION_PREFIX,
    calculate_grandstand_angle,
    calculate_grandstand_height,
    generate_building,
    get_template_values,
    int_or_default,
    list_template_names,
    remove_template,
    save_template,
    write_3d,
)


def _base_parameters():
    return {
        "building_shape": "rectangular",
        "width": 320,
        "depth": 1042,
        "height": 100,
        "diameter": 320,
        "num_sides": 12,
        "roof_type": "flat",
        "parapet_inset": 30,
        "parapet_height": 15,
        "gable_rise": 50,
        "pyramid_rise": 50,
        "dome_layers": 4,
        "dome_roundness": 100,
        "sunny_pcx": "C:/game/sunny.pcx",
        "roof_color_bright": 200,
        "roof_color_dark": 201,
        "side_color_bright": 202,
        "side_color_dark": 203,
        "tree_trunk_width": 30,
        "tree_leaf_base_height": 100,
        "tree_trunk_color": 96,
        "tree_leaves_color": 120,
        "tree_num_sides": 12,
        "tree_trunk_color_bright": 96,
        "tree_trunk_color_dark": 97,
        "tree_leaves_color_bright": 120,
        "tree_leaves_color_dark": 121,
        "bridge_length": 320,
        "bridge_width": 80,
        "bridge_clearance": 100,
        "bridge_height": 20,
        "bridge_half": False,
    }


def test_write_3d_puts_comments_after_header_and_colors_polys(tmp_path: Path):
    verts, faces = generate_building(320, 1042, 100, "flat", 30, 15, 50, 50)
    out = tmp_path / "building.3D"

    write_3d(out, verts, faces, _base_parameters())

    lines = out.read_text(encoding="utf-8").splitlines()
    assert lines[0] == "3D VERSION 3.0;"
    assert lines[1].startswith("% Generated by ICR2 Building Generator")
    assert any(line.startswith("% width:") for line in lines[2:10])

    poly_lines = [line for line in lines if ": POLY <" in line]
    assert any("topB: POLY <200>" in line for line in poly_lines)
    assert any("topD: POLY <200>" in line for line in poly_lines)
    assert any("ls1: POLY <202>" in line for line in poly_lines)
    assert any("rs1: POLY <203>" in line for line in poly_lines)


def test_gable_uses_roof_colors_for_slopes_and_side_colors_for_end_walls(tmp_path: Path):
    verts, faces = generate_building(320, 1042, 100, "gable", 30, 15, 50, 50)
    out = tmp_path / "gable.3D"

    params = _base_parameters()
    params["roof_type"] = "gable"
    write_3d(out, verts, faces, params)

    text = out.read_text(encoding="utf-8")
    assert "roofL: POLY <200>" in text
    assert "roofR: POLY <201>" in text
    assert "gableF: POLY <202>" in text
    assert "gableB: POLY <203>" in text


def test_parapet_uses_roof_colors_for_upper_sides_and_bright_top(tmp_path: Path):
    verts, faces = generate_building(320, 1042, 100, "parapet", 30, 15, 50, 50)
    out = tmp_path / "parapet.3D"

    params = _base_parameters()
    params["roof_type"] = "parapet"
    write_3d(out, verts, faces, params)

    text = out.read_text(encoding="utf-8")
    assert "ls2: POLY <200>" in text
    assert "fr2: POLY <200>" in text
    assert "rs2: POLY <201>" in text
    assert "bk2: POLY <201>" in text
    assert "roofB: POLY <200>" in text
    assert "roofD: POLY <200>" in text


def test_template_roundtrip_and_listing_order():
    cfg = configparser.ConfigParser()
    save_template(
        cfg,
        "B Tower",
        {"building_shape": "rectangular", "width": 123, "roof_type": "gable", "side_color_dark": 222},
    )
    save_template(cfg, "A Tower", {"depth": 456, "roof_type": "flat"})

    assert list_template_names(cfg) == ["A Tower", "B Tower"]

    values = get_template_values(cfg, "B Tower")
    assert values is not None
    assert values["building_shape"] == "rectangular"
    assert values["width"] == "123"
    assert values["roof_type"] == "gable"
    assert values["side_color_dark"] == "222"
    assert values["depth"] == ""


def test_none_roof_omits_roof_faces():
    _verts, faces = generate_building(320, 1042, 100, "none", 30, 15, 50, 50)
    names = {name for name, _ in faces}
    assert not names.intersection({"topB", "topD", "roofB", "roofD", "roofL", "roofR", "pyrF"})




def test_circular_building_vertices_keep_up_to_two_decimal_places():
    verts, _faces = generate_building(
        0,
        0,
        120,
        "flat",
        0,
        0,
        0,
        0,
        building_shape="circular",
        diameter=200,
        num_sides=12,
    )

    x, y, _z = verts["cb1"]
    assert isinstance(x, float)
    assert isinstance(y, float)
    assert x == 86.6
    assert y == 50.0


def test_circular_dome_building_uses_requested_sides_and_layers(tmp_path: Path):
    verts, faces = generate_building(
        0,
        0,
        120,
        "dome",
        0,
        0,
        0,
        0,
        building_shape="circular",
        diameter=200,
        num_sides=8,
        dome_layers=3,
    )
    out = tmp_path / "circular_dome.3D"
    params = _base_parameters()
    params.update({"building_shape": "circular", "roof_type": "dome"})

    write_3d(out, verts, faces, params)
    text = out.read_text(encoding="utf-8")
    assert "dome_top:" in text
    assert any(name.startswith("sideB") or name.startswith("sideD") for name, _ in faces)
    assert any(name.startswith("roofB") or name.startswith("roofD") for name, _ in faces)


def test_circular_dome_profile_is_curved_not_linear():
    verts, _faces = generate_building(
        0,
        0,
        120,
        "dome",
        0,
        0,
        0,
        0,
        building_shape="circular",
        diameter=200,
        num_sides=8,
        dome_layers=3,
    )

    # With a curved (quarter-circle) profile, the first ring keeps more radius
    # while also rising more than a linear cone profile.
    assert verts["dr1_0"][0] > 90
    assert verts["dr1_0"][2] > 145


def test_remove_template_deletes_section():
    cfg = configparser.ConfigParser()
    save_template(cfg, "Warehouse", {"width": 200})

    remove_template(cfg, "Warehouse")

    assert not cfg.has_section(f"{TEMPLATE_SECTION_PREFIX}Warehouse")
    assert get_template_values(cfg, "Warehouse") is None


def test_circular_dome_roundness_zero_uses_flat_roof():
    verts, faces = generate_building(
        0,
        0,
        120,
        "dome",
        0,
        0,
        0,
        0,
        building_shape="circular",
        diameter=200,
        num_sides=12,
        dome_layers=4,
        dome_roundness=0,
    )

    assert "dome_top" not in verts
    assert "ctp" in verts
    assert any(name.startswith("roofB") or name.startswith("roofD") for name, _ in faces)


def test_circular_dome_roundness_changes_dome_height():
    flat_verts, _ = generate_building(
        0,
        0,
        120,
        "dome",
        0,
        0,
        0,
        0,
        building_shape="circular",
        diameter=200,
        num_sides=12,
        dome_layers=4,
        dome_roundness=25,
    )
    round_verts, _ = generate_building(
        0,
        0,
        120,
        "dome",
        0,
        0,
        0,
        0,
        building_shape="circular",
        diameter=200,
        num_sides=12,
        dome_layers=4,
        dome_roundness=100,
    )

    assert flat_verts["dome_top"][2] < round_verts["dome_top"][2]


def test_circular_dome_roundness_still_curves_to_top():
    verts, _ = generate_building(
        0,
        0,
        120,
        "dome",
        0,
        0,
        0,
        0,
        building_shape="circular",
        diameter=200,
        num_sides=12,
        dome_layers=4,
        dome_roundness=25,
    )

    # Even when flattened, the roof should keep curving inward instead of
    # staying near full radius with a sudden top cap.
    assert verts["dr4_0"][0] < 150




def test_tree_shape_generates_trunk_and_leaf_faces():
    verts, faces = generate_building(
        180,
        0,
        300,
        "none",
        0,
        0,
        0,
        0,
        building_shape="tree",
        tree_trunk_width=40,
        tree_leaf_base_height=120,
        tree_num_sides=10,
    )

    assert verts["tb0"] == (20, 0, 0)
    assert verts["tt0"] == (20, 0, 120)
    assert verts["tb1"][2] == 0
    assert verts["tt1"][2] == 120
    assert any(name.startswith("trunkB") for name, _ in faces)
    assert any(name.startswith("trunkD") for name, _ in faces)
    assert any(name.startswith("leafB") for name, _ in faces)
    assert any(name.startswith("leafD") for name, _ in faces)


def test_tree_shape_uses_tree_colors(tmp_path: Path):
    verts, faces = generate_building(
        180,
        0,
        300,
        "none",
        0,
        0,
        0,
        0,
        building_shape="tree",
        tree_trunk_width=50,
        tree_leaf_base_height=140,
        tree_num_sides=9,
    )
    out = tmp_path / "tree.3D"

    params = _base_parameters()
    params.update(
        {
            "building_shape": "tree",
            "roof_type": "none",
            "tree_trunk_color_bright": 88,
            "tree_trunk_color_dark": 66,
            "tree_leaves_color_bright": 132,
            "tree_leaves_color_dark": 111,
        }
    )
    write_3d(out, verts, faces, params)

    text = out.read_text(encoding="utf-8")
    assert "trunkB0: POLY <88>" in text
    assert "trunkD" in text and "POLY <66>" in text
    assert "leafB" in text and "POLY <132>" in text
    assert "leafD" in text and "POLY <111>" in text


def test_tree_shape_respects_requested_sides_for_circular_profile():
    _verts, faces = generate_building(
        180,
        0,
        300,
        "none",
        0,
        0,
        0,
        0,
        building_shape="tree",
        tree_trunk_width=40,
        tree_leaf_base_height=120,
        tree_num_sides=7,
    )

    trunk_faces = [name for name, _ in faces if name.startswith("trunk")]
    leaf_side_faces = [name for name, _ in faces if name.startswith("leaf") and "S" in name]
    assert len(trunk_faces) == 7
    assert len(leaf_side_faces) == 7


def test_tree_shape_avoids_degenerate_trunk_faces_with_small_radius():
    verts, faces = generate_building(
        20,
        0,
        30,
        "none",
        0,
        0,
        0,
        0,
        building_shape="tree",
        tree_trunk_width=2,
        tree_leaf_base_height=5,
        tree_num_sides=12,
    )

    trunk_faces = [vs for name, vs in faces if name.startswith("trunk")]
    assert trunk_faces
    for vs in trunk_faces:
        unique_coords = {verts[v] for v in vs}
        assert len(unique_coords) >= 3


def test_tree_shape_round_profile_creates_multi_ring_canopy():
    verts, faces = generate_building(
        180,
        0,
        300,
        "none",
        0,
        0,
        0,
        0,
        building_shape="tree",
        tree_trunk_width=40,
        tree_leaf_base_height=120,
        tree_num_sides=8,
        tree_profile="round",
    )

    assert verts["leaf_bottom_center"][2] == 120
    assert verts["leaf_top_center"][2] == 300
    assert "lr1_0" in verts
    assert "lr4_0" in verts
    assert any(name.startswith("leafB") and "S0_" in name for name, _ in faces)


def test_tree_shape_unknown_profile_falls_back_to_pointy():
    verts, _faces = generate_building(
        180,
        0,
        300,
        "none",
        0,
        0,
        0,
        0,
        building_shape="tree",
        tree_trunk_width=40,
        tree_leaf_base_height=120,
        tree_num_sides=8,
        tree_profile="unknown-profile",
    )

    assert "lb0" in verts
    assert "lm0" in verts


def test_tree_pointy_profile_leaf_bottom_faces_wind_downward():
    _verts, faces = generate_building(
        180,
        0,
        300,
        "none",
        0,
        0,
        0,
        0,
        building_shape="tree",
        tree_trunk_width=40,
        tree_leaf_base_height=120,
        tree_num_sides=8,
        tree_profile="pointy",
    )

    face_lookup = {name: vs for name, vs in faces}
    assert face_lookup["leafBB0"] == ["leaf_bottom_center", "lb1", "lb0"]
    assert face_lookup["leafDB4"] == ["leaf_bottom_center", "lb5", "lb4"]


def test_tree_round_profile_leaf_bottom_faces_wind_downward():
    _verts, faces = generate_building(
        180,
        0,
        300,
        "none",
        0,
        0,
        0,
        0,
        building_shape="tree",
        tree_trunk_width=40,
        tree_leaf_base_height=120,
        tree_num_sides=8,
        tree_profile="round",
    )

    face_lookup = {name: vs for name, vs in faces}
    assert face_lookup["leafBB0"] == ["leaf_bottom_center", "lr1_1", "lr1_0"]
    assert face_lookup["leafDB4"] == ["leaf_bottom_center", "lr1_5", "lr1_4"]


def test_tree_palm_profile_generates_fronds_from_trunk_top_with_mixed_curves():
    leaf_base_height = 120
    verts, faces = generate_building(
        180,
        0,
        300,
        "none",
        0,
        0,
        0,
        0,
        building_shape="tree",
        tree_trunk_width=40,
        tree_leaf_base_height=leaf_base_height,
        tree_num_sides=8,
        tree_profile="palm",
    )

    assert "leaf_crown_center" in verts
    assert verts["leaf_crown_center"][2] == leaf_base_height
    assert any(name.startswith("pfb") for name in verts)
    stem_inner_names = [name for name, _ in faces if "PalmStemInner" in name]
    blade_inner_names = [name for name, _ in faces if "PalmBladeInner" in name]
    stem_outer_names = [name for name, _ in faces if "PalmStemOuter" in name]
    blade_outer_names = [name for name, _ in faces if "PalmBladeOuter" in name]
    assert stem_inner_names and blade_inner_names and stem_outer_names and blade_outer_names

    first_outer_index = min(
        idx for idx, (name, _vs) in enumerate(faces) if "PalmStemOuter" in name or "PalmBladeOuter" in name
    )
    last_inner_index = max(
        idx for idx, (name, _vs) in enumerate(faces) if "PalmStemInner" in name or "PalmBladeInner" in name
    )
    assert last_inner_index < first_outer_index

    assert verts["pft0"][2] < verts["pfb0"][2]
    assert verts["pfl0"][2] > verts["pfb0"][2]
    assert verts["pft1"][2] < verts["pfl1"][2] < verts["pfb1"][2]


def test_tree_unknown_profile_still_falls_back_to_pointy_not_palm():
    verts, _faces = generate_building(
        180,
        0,
        300,
        "none",
        0,
        0,
        0,
        0,
        building_shape="tree",
        tree_trunk_width=40,
        tree_leaf_base_height=120,
        tree_num_sides=8,
        tree_profile="something-else",
    )

    assert "leaf_crown_center" not in verts
    assert "lb0" in verts
    assert "lm0" in verts


def test_rect_center_origin_offsets_gable_roof_vertices_consistently():
    verts, _faces = generate_building(
        320,
        1042,
        100,
        "gable",
        30,
        15,
        50,
        50,
        rect_center_origin=True,
    )

    assert verts["a1"][0] == -160
    assert verts["a1"][1] == 521
    assert verts["r0"][0] == 0
    assert verts["r1"][0] == 0
    assert verts["r0"][1] == -521
    assert verts["r1"][1] == 521


def test_int_or_default_uses_default_for_blank_and_invalid_values():
    assert int_or_default("", 7) == 7
    assert int_or_default("   ", 8) == 8
    assert int_or_default(None, 9) == 9
    assert int_or_default("abc", 10) == 10
    assert int_or_default("12", 0) == 12


def test_bridge_shape_generates_walkway_and_45_degree_slopes():
    verts, faces = generate_building(
        0,
        0,
        0,
        "none",
        0,
        0,
        0,
        0,
        building_shape="bridge",
        bridge_length=300,
        bridge_width=70,
        bridge_clearance=120,
        bridge_height=24,
    )

    assert verts["f1"] == (-150.0, -35.0, 120)
    assert verts["f2"] == (150.0, -35.0, 120)
    assert verts["f6"] == (-150.0, -35.0, 144)
    assert verts["f0"] == (-270.0, -35.0, 0)
    assert verts["b0"] == (-270.0, 35.0, 0)
    assert verts["f1"][2] - verts["f0"][2] == verts["f1"][0] - verts["f0"][0]
    assert verts["f3"][2] - verts["f2"][2] == -(verts["f3"][0] - verts["f2"][0])

    names = {name for name, _ in faces}
    assert {"topRampL", "topBridge", "topRampR", "botRampL", "botBridge", "botRampR"}.issubset(names)


def test_bridge_shape_uses_side_top_and_bottom_colors(tmp_path: Path):
    verts, faces = generate_building(
        0,
        0,
        0,
        "none",
        0,
        0,
        0,
        0,
        building_shape="bridge",
        bridge_length=300,
        bridge_width=70,
        bridge_clearance=120,
        bridge_height=24,
    )
    out = tmp_path / "bridge.3D"

    params = _base_parameters()
    params.update(
        {
            "building_shape": "bridge",
            "roof_type": "none",
            "roof_color_bright": 140,
            "roof_color_dark": 141,
            "side_color_bright": 18,
            "side_color_dark": 19,
        }
    )

    write_3d(out, verts, faces, params)

    text = out.read_text(encoding="utf-8")
    assert "lsLeft: POLY <18>" in text
    assert "lsCenter: POLY <18>" in text
    assert "lsRight: POLY <18>" in text
    assert "rsLeft: POLY <19>" in text
    assert "rsCenter: POLY <19>" in text
    assert "rsRight: POLY <19>" in text
    assert "topBridge: POLY <140>" in text
    assert "botBridge: POLY <141>" in text


def test_bridge_sides_are_split_into_three_quads_per_side():
    _verts, faces = generate_building(
        0,
        0,
        0,
        "none",
        0,
        0,
        0,
        0,
        building_shape="bridge",
        bridge_length=320,
        bridge_width=80,
        bridge_clearance=100,
        bridge_height=20,
    )

    face_map = {name: points for name, points in faces}
    for side_name in ("lsLeft", "lsCenter", "lsRight", "rsLeft", "rsCenter", "rsRight"):
        assert side_name in face_map
        assert len(face_map[side_name]) == 4

    assert "ls1" not in face_map
    assert "rs1" not in face_map

    assert all(len(points) <= 4 for _name, points in faces)


def test_bridge_half_is_open_on_chopped_side_and_aligned_to_vertical_axis():
    verts, faces = generate_building(
        0,
        0,
        0,
        "none",
        0,
        0,
        0,
        0,
        building_shape="bridge",
        bridge_length=320,
        bridge_width=80,
        bridge_clearance=100,
        bridge_height=20,
        bridge_half=True,
    )

    face_map = {name: points for name, points in faces}
    assert "bk1" not in face_map

    assert "lsRight" not in face_map
    assert "rsRight" not in face_map

    # Chopped opening lies on x=0 for easy mirrored placement.
    assert verts["f2"][0] == 0
    assert verts["f3"][0] == 0
    assert verts["b2"][0] == 0
    assert verts["b3"][0] == 0

    # Bridge remains centered about y=0 while keeping ground at z=0.
    assert verts["f0"][1] == -40.0
    assert verts["b0"][1] == 40.0
    assert min(point[2] for point in verts.values()) == 0

    assert all(len(points) <= 4 for _name, points in faces)


def test_grandstand_height_calculates_from_angle_and_front_height():
    assert calculate_grandstand_height(120, 39.8, 0) == 100
    assert calculate_grandstand_height(120, 39.8, 25) == 125


def test_grandstand_angle_calculates_from_width_height_and_front_height():
    assert round(calculate_grandstand_angle(120, 100, 0), 1) == 39.8
    assert round(calculate_grandstand_angle(120, 125, 25), 1) == 39.8

def test_grandstand_supports_front_height_offset():
    verts, _faces = generate_building(
        0,
        0,
        0,
        "none",
        0,
        0,
        0,
        0,
        building_shape="grandstand",
        grandstand_length=300,
        grandstand_width=120,
        grandstand_height=140,
        grandstand_front_height=40,
    )

    assert verts["gs_tf_l"][2] == 40
    assert verts["gs_tb_l"][2] == 140
    assert verts["gs_bf_l"][2] == 0

def test_grandstand_shape_generates_simple_sloped_building_faces():
    verts, faces = generate_building(
        0,
        0,
        0,
        "none",
        0,
        0,
        0,
        0,
        building_shape="grandstand",
        grandstand_length=300,
        grandstand_width=120,
        grandstand_height=90,
    )

    names = {name for name, _ in faces}
    assert names == {"seatB", "seatD", "seatBack", "seatLs", "seatRs"}

    assert verts["gs_tb_l"][2] == 90
    assert verts["gs_bb_l"][2] == 0
    assert all(verts[name][2] == 0 for name in {"gs_tf_l", "gs_tf_r", "gs_bf_l", "gs_bf_r", "gs_bb_l", "gs_bb_r"})


def test_grandstand_uses_user_colors_for_seats_and_sides(tmp_path: Path):
    verts, faces = generate_building(
        0,
        0,
        0,
        "none",
        0,
        0,
        0,
        0,
        building_shape="grandstand",
        grandstand_length=280,
        grandstand_width=110,
        grandstand_height=80,
    )
    out = tmp_path / "grandstand.3D"

    params = _base_parameters()
    params.update(
        {
            "building_shape": "grandstand",
            "roof_type": "none",
            "roof_color_bright": 44,
            "roof_color_dark": 45,
            "side_color_bright": 46,
            "side_color_dark": 47,
        }
    )

    write_3d(out, verts, faces, params)

    text = out.read_text(encoding="utf-8")
    assert "seatB: POLY <44>" in text
    assert "seatD: POLY <45>" in text
    assert "seatBack: POLY <44>" in text
    assert "seatLs: POLY <46>" in text
    assert "seatRs: POLY <46>" in text


def test_grandstand_adds_front_face_when_front_height_is_nonzero():
    _verts, faces = generate_building(
        0,
        0,
        0,
        "none",
        0,
        0,
        0,
        0,
        building_shape="grandstand",
        grandstand_length=300,
        grandstand_width=120,
        grandstand_height=140,
        grandstand_front_height=40,
    )

    face_map = {name: points for name, points in faces}
    assert "seatFront" in face_map
    assert face_map["seatFront"] == ["gs_tf_l", "gs_bf_l", "gs_bf_r", "gs_tf_r"]

