import configparser
from pathlib import Path

from tso_generator.tso_generator import (
    TEMPLATE_SECTION_PREFIX,
    generate_building,
    get_template_values,
    list_template_names,
    remove_template,
    save_template,
    write_3d,
)


def _base_parameters():
    return {
        "width": 320,
        "depth": 1042,
        "height": 100,
        "roof_type": "flat",
        "parapet_inset": 30,
        "parapet_height": 15,
        "gable_rise": 50,
        "pyramid_rise": 50,
        "sunny_pcx": "C:/game/sunny.pcx",
        "roof_color_bright": 200,
        "roof_color_dark": 201,
        "side_color_bright": 202,
        "side_color_dark": 203,
    }


def test_write_3d_puts_comments_after_header_and_colors_polys(tmp_path: Path):
    verts, faces = generate_building(320, 1042, 100, "flat", 30, 15, 50, 50)
    out = tmp_path / "building.3D"

    write_3d(out, verts, faces, _base_parameters())

    lines = out.read_text(encoding="utf-8").splitlines()
    assert lines[0] == "3D VERSION 3.0;"
    assert lines[1].startswith("% Generated by ICR2 Building Generator")
    assert any(line.startswith("% width:") for line in lines[2:10])

    poly_lines = [line for line in lines if ": POLY <" in line]
    assert any("topB: POLY <200>" in line for line in poly_lines)
    assert any("topD: POLY <201>" in line for line in poly_lines)
    assert any("ls1: POLY <202>" in line for line in poly_lines)
    assert any("rs1: POLY <203>" in line for line in poly_lines)


def test_gable_uses_roof_colors_for_slopes_and_side_colors_for_end_walls(tmp_path: Path):
    verts, faces = generate_building(320, 1042, 100, "gable", 30, 15, 50, 50)
    out = tmp_path / "gable.3D"

    params = _base_parameters()
    params["roof_type"] = "gable"
    write_3d(out, verts, faces, params)

    text = out.read_text(encoding="utf-8")
    assert "roofL: POLY <200>" in text
    assert "roofR: POLY <201>" in text
    assert "gableF: POLY <202>" in text
    assert "gableB: POLY <203>" in text


def test_template_roundtrip_and_listing_order():
    cfg = configparser.ConfigParser()
    save_template(cfg, "B Tower", {"width": 123, "roof_type": "gable", "side_color_dark": 222})
    save_template(cfg, "A Tower", {"depth": 456, "roof_type": "flat"})

    assert list_template_names(cfg) == ["A Tower", "B Tower"]

    values = get_template_values(cfg, "B Tower")
    assert values is not None
    assert values["width"] == "123"
    assert values["roof_type"] == "gable"
    assert values["side_color_dark"] == "222"
    assert values["depth"] == ""


def test_remove_template_deletes_section():
    cfg = configparser.ConfigParser()
    save_template(cfg, "Warehouse", {"width": 200})

    remove_template(cfg, "Warehouse")

    assert not cfg.has_section(f"{TEMPLATE_SECTION_PREFIX}Warehouse")
    assert get_template_values(cfg, "Warehouse") is None
