"""Track TXT tab builder for the track viewer."""
from __future__ import annotations

from PyQt5 import QtCore, QtWidgets


class TrackTxtTabBuilder:
    """Builds the track.txt tab UI and wires signals."""

    def __init__(self, window: QtWidgets.QWidget) -> None:
        self._window = window

    def build(self) -> QtWidgets.QWidget:
        window = self._window
        window._track_txt_status_label = QtWidgets.QLabel(
            "Select a track to edit track.txt parameters."
        )
        window._track_txt_status_label.setWordWrap(True)
        window._track_name_field = window._create_text_field("–")
        window._track_short_name_field = window._create_text_field("–")
        window._track_city_field = window._create_text_field("–")
        window._track_country_field = window._create_text_field("–")
        window._track_pit_window_start_field = window._create_int_field("–")
        window._track_pit_window_end_field = window._create_int_field("–")
        window._track_length_field = window._create_int_field("–")
        window._track_laps_field = window._create_int_field("–")
        window._track_full_name_field = window._create_text_field("–")
        window._cars_min_field = window._create_int_field("–")
        window._cars_max_field = window._create_int_field("–")
        window._blap_field = window._create_int_field("–")
        window._rels_field = window._create_int_field("–")
        window._sctns_fields = [window._create_int_field("–") for _ in range(3)]
        window._qual_mode_field = QtWidgets.QComboBox()
        window._qual_mode_field.addItem("0 - timed session", 0)
        window._qual_mode_field.addItem("1 - multi-lap average", 1)
        window._qual_mode_field.addItem("2 - best single lap", 2)
        window._qual_mode_field.setCurrentIndex(-1)
        window._qual_mode_field.currentIndexChanged.connect(
            window._handle_qual_mode_changed
        )
        window._qual_value_field = window._create_int_field("–")
        window._qual_value_label = QtWidgets.QLabel("Value")
        window._blimp_x_field = window._create_int_field("–")
        window._blimp_y_field = window._create_int_field("–")
        window._gflag_field = window._create_int_field("–")
        window._ttype_field = QtWidgets.QComboBox()
        window._ttype_field.addItem("0 - short oval", 0)
        window._ttype_field.addItem("1 - mid oval", 1)
        window._ttype_field.addItem("2 - large oval", 2)
        window._ttype_field.addItem("3 - superspeedway", 3)
        window._ttype_field.addItem("4 - road course", 4)
        window._ttype_field.addItem("5 - unknown", 5)
        window._ttype_field.setCurrentIndex(-1)
        window._pacea_cars_abreast_field = window._create_int_field("–")
        window._pacea_start_dlong_field = window._create_int_field("–")
        window._pacea_right_dlat_field = window._create_int_field("–")
        window._pacea_left_dlat_field = window._create_int_field("–")
        window._pacea_unknown_field = window._create_int_field("–")
        window._track_txt_save_button = QtWidgets.QPushButton("Save Track TXT")
        window._track_txt_save_button.setEnabled(False)
        window._track_txt_save_button.clicked.connect(
            window._handle_save_track_txt
        )

        track_txt_sidebar = QtWidgets.QFrame()
        track_txt_sidebar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        track_txt_layout = QtWidgets.QVBoxLayout()
        track_txt_layout.setSpacing(8)
        track_txt_title = QtWidgets.QLabel("Track TXT parameters")
        track_txt_title.setStyleSheet("font-weight: bold")
        track_txt_layout.addWidget(track_txt_title)
        track_txt_layout.addWidget(window._track_txt_status_label)
        track_txt_form = QtWidgets.QFormLayout()
        track_txt_form.setLabelAlignment(QtCore.Qt.AlignLeft)
        track_txt_form.setFormAlignment(QtCore.Qt.AlignTop)
        track_name_layout = QtWidgets.QHBoxLayout()
        track_name_layout.setContentsMargins(0, 0, 0, 0)
        track_name_layout.addWidget(QtWidgets.QLabel("Track name (TNAME)"))
        track_name_layout.addWidget(window._track_name_field)
        track_name_layout.addWidget(QtWidgets.QLabel("Short name (SNAME)"))
        track_name_layout.addWidget(window._track_short_name_field)
        track_name_widget = QtWidgets.QWidget()
        track_name_widget.setLayout(track_name_layout)
        track_txt_form.addRow(track_name_widget)
        track_location_layout = QtWidgets.QHBoxLayout()
        track_location_layout.setContentsMargins(0, 0, 0, 0)
        track_location_layout.addWidget(QtWidgets.QLabel("City (CITYN)"))
        track_location_layout.addWidget(window._track_city_field)
        track_location_layout.addWidget(QtWidgets.QLabel("Country (COUNT)"))
        track_location_layout.addWidget(window._track_country_field)
        track_location_widget = QtWidgets.QWidget()
        track_location_widget.setLayout(track_location_layout)
        track_txt_form.addRow(track_location_widget)
        spdwy_layout = QtWidgets.QHBoxLayout()
        spdwy_layout.setContentsMargins(0, 0, 0, 0)
        spdwy_layout.addWidget(QtWidgets.QLabel("Start"))
        spdwy_layout.addWidget(window._track_pit_window_start_field)
        spdwy_layout.addWidget(QtWidgets.QLabel("End"))
        spdwy_layout.addWidget(window._track_pit_window_end_field)
        spdwy_widget = QtWidgets.QWidget()
        spdwy_widget.setLayout(spdwy_layout)
        track_txt_form.addRow("Pit window (SPDWY)", spdwy_widget)
        track_length_layout = QtWidgets.QHBoxLayout()
        track_length_layout.setContentsMargins(0, 0, 0, 0)
        track_length_layout.addWidget(QtWidgets.QLabel("Length (LENGT)"))
        track_length_layout.addWidget(window._track_length_field)
        track_length_layout.addWidget(QtWidgets.QLabel("Laps (LAPS)"))
        track_length_layout.addWidget(window._track_laps_field)
        track_length_widget = QtWidgets.QWidget()
        track_length_widget.setLayout(track_length_layout)
        track_txt_form.addRow(track_length_widget)
        track_txt_form.addRow("Full name (FNAME)", window._track_full_name_field)
        cars_layout = QtWidgets.QHBoxLayout()
        cars_layout.setContentsMargins(0, 0, 0, 0)
        cars_layout.addWidget(QtWidgets.QLabel("Unknown"))
        cars_layout.addWidget(window._cars_min_field)
        cars_layout.addWidget(QtWidgets.QLabel("Cars"))
        cars_layout.addWidget(window._cars_max_field)
        cars_widget = QtWidgets.QWidget()
        cars_widget.setLayout(cars_layout)
        track_txt_form.addRow("Cars (CARS)", cars_widget)
        track_txt_form.addRow("Pole lap (BLAP)", window._blap_field)
        track_txt_form.addRow("Relative strength (RELS)", window._rels_field)
        track_txt_form.addRow(
            "Sections (SCTNS)",
            window._build_number_row(window._sctns_fields),
        )
        qual_layout = QtWidgets.QHBoxLayout()
        qual_layout.setContentsMargins(0, 0, 0, 0)
        qual_layout.addWidget(QtWidgets.QLabel("Mode"))
        qual_layout.addWidget(window._qual_mode_field)
        qual_layout.addWidget(window._qual_value_label)
        qual_layout.addWidget(window._qual_value_field)
        qual_widget = QtWidgets.QWidget()
        qual_widget.setLayout(qual_layout)
        track_txt_form.addRow("Qualifying (QUAL)", qual_widget)
        blimp_layout = QtWidgets.QHBoxLayout()
        blimp_layout.setContentsMargins(0, 0, 0, 0)
        blimp_layout.addWidget(QtWidgets.QLabel("X"))
        blimp_layout.addWidget(window._blimp_x_field)
        blimp_layout.addWidget(QtWidgets.QLabel("Y"))
        blimp_layout.addWidget(window._blimp_y_field)
        blimp_widget = QtWidgets.QWidget()
        blimp_widget.setLayout(blimp_layout)
        track_txt_form.addRow("Blimp position (BLIMP)", blimp_widget)
        track_txt_form.addRow("Green flag DLONG (GFLAG)", window._gflag_field)
        track_txt_form.addRow("Track type (TTYPE)", window._ttype_field)
        pacea_layout = QtWidgets.QGridLayout()
        pacea_layout.setContentsMargins(0, 0, 0, 0)
        pacea_layout.setHorizontalSpacing(6)
        pacea_layout.addWidget(QtWidgets.QLabel("Cars"), 0, 0)
        pacea_layout.addWidget(window._pacea_cars_abreast_field, 0, 1)
        pacea_layout.addWidget(QtWidgets.QLabel("Start DLONG"), 0, 2)
        pacea_layout.addWidget(window._pacea_start_dlong_field, 0, 3)
        pacea_layout.addWidget(QtWidgets.QLabel("Right DLAT"), 1, 0)
        pacea_layout.addWidget(window._pacea_right_dlat_field, 1, 1)
        pacea_layout.addWidget(QtWidgets.QLabel("Left DLAT"), 1, 2)
        pacea_layout.addWidget(window._pacea_left_dlat_field, 1, 3)
        pacea_layout.addWidget(QtWidgets.QLabel("Unknown"), 2, 0)
        pacea_layout.addWidget(window._pacea_unknown_field, 2, 1)
        pacea_widget = QtWidgets.QWidget()
        pacea_widget.setLayout(pacea_layout)
        track_txt_form.addRow("Pace lap (PACEA)", pacea_widget)
        track_txt_layout.addLayout(track_txt_form)
        track_txt_layout.addStretch(1)
        track_txt_layout.addWidget(window._track_txt_save_button)
        track_txt_sidebar.setLayout(track_txt_layout)
        track_txt_scroll = QtWidgets.QScrollArea()
        track_txt_scroll.setFrameShape(QtWidgets.QFrame.NoFrame)
        track_txt_scroll.setHorizontalScrollBarPolicy(
            QtCore.Qt.ScrollBarAlwaysOff
        )
        track_txt_scroll.setVerticalScrollBarPolicy(
            QtCore.Qt.ScrollBarAsNeeded
        )
        track_txt_scroll.setWidgetResizable(True)
        track_txt_scroll.setWidget(track_txt_sidebar)
        return track_txt_scroll
